//go:build interop

// Package interop runs the agent against the real Python emulator in
// ../OrderEchoFixEmulator. Every test starts its own emulator with all storage
// in a temp dir and random free ports, and kills it at the end.
package interop

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	oeagent "github.com/danielgavin-code/OrderEcho/internal/agent"
	"github.com/danielgavin-code/OrderEcho/internal/clock"
	"github.com/danielgavin-code/OrderEcho/internal/config"
	"github.com/danielgavin-code/OrderEcho/internal/evidence"
	"github.com/danielgavin-code/OrderEcho/internal/fix/session"
	"github.com/danielgavin-code/OrderEcho/internal/fix/transport"
	"github.com/danielgavin-code/OrderEcho/internal/logs"
)

var (
	repoRoot    string
	emulatorDir string
	pythonBin   string
	agentBin    string // built once in TestMain
	skipReason  string
)

func TestMain(m *testing.M) {
	wd, _ := os.Getwd()
	repoRoot = findRepoRoot(wd)
	emulatorDir = filepath.Clean(filepath.Join(repoRoot, "..", "OrderEchoFixEmulator"))
	pythonBin = filepath.Join(emulatorDir, ".venv", "bin", "python")
	switch {
	case !exists(filepath.Join(emulatorDir, "orderecho_Main.py")):
		skipReason = "emulator not found at " + emulatorDir
	case !exists(pythonBin):
		skipReason = "emulator venv not found at " + pythonBin
	}
	code := 0
	if skipReason == "" {
		dir, err := os.MkdirTemp("", "orderecho-interop-bin")
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		agentBin = filepath.Join(dir, "orderecho")
		build := exec.Command("go", "build", "-o", agentBin, "./cmd/orderecho")
		build.Dir = repoRoot
		if out, err := build.CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "building agent: %v\n%s", err, out)
			os.Exit(1)
		}
		code = m.Run()
		printParitySummary()
		os.RemoveAll(dir)
	} else {
		code = m.Run()
	}
	os.Exit(code)
}

func findRepoRoot(dir string) string {
	for d := dir; ; d = filepath.Dir(d) {
		if exists(filepath.Join(d, "go.mod")) {
			return d
		}
		if filepath.Dir(d) == d {
			return dir
		}
	}
}

func exists(p string) bool { _, err := os.Stat(p); return err == nil }

func requireEmulator(t *testing.T) {
	t.Helper()
	if skipReason != "" {
		t.Skip("interop: " + skipReason)
	}
}

func freePort(t *testing.T) int {
	t.Helper()
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer l.Close()
	return l.Addr().(*net.TCPAddr).Port
}

func waitFor(t *testing.T, timeout time.Duration, what string, cond func() bool) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if cond() {
			return
		}
		time.Sleep(50 * time.Millisecond)
	}
	t.Fatalf("timed out after %s waiting for %s", timeout, what)
}

// ------------------------------------------------------------ emulator

type emulator struct {
	t          *testing.T
	dir        string
	fixPort    int
	strictPort int
	apiPort    int
	cmd        *exec.Cmd
	out        *lockedBuffer
}

type lockedBuffer struct {
	mu  sync.Mutex
	buf bytes.Buffer
}

func (b *lockedBuffer) Write(p []byte) (int, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.Write(p)
}

func (b *lockedBuffer) String() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.String()
}

// emulatorConfig mirrors ../OrderEchoFixEmulator/config/orderecho_multi.yaml
// (same sessions, rules and bands) with static pricing, temp storage and
// random ports.
const emulatorConfig = `# generated by the OrderEcho interop tests
engine: { host: 127.0.0.1, fix_port: %d, default_session: agent42, logon_timeout_sec: 10 }
defaults:
  heartbeat_grace_pct: 20
  logout_timeout_sec: 10
  resend_mode: replay
  orders: { default_delay_ms: 500, send_pending_acks: false, replace_ack_ordstatus: current }
  price_band: { enabled: true, pct: 10, mode: aggressive, enforce_on_fallback: false, lookup_timeout_ms: 3000, on_no_reference: skip }
  rules:
    - { name: nasdaq-test-reject, match: { symbol: ZVZZT }, behavior: reject, reject_code: 1, text: "Unknown symbol" }
    - { name: nasdaq-test-hold, match: { symbol: ZWZZT }, behavior: ack_only }
    - { name: a-to-d-full, match: { first_letter: "A-D" }, behavior: full_fill }
    - { name: e-to-g-partial, match: { first_letter: "E-G" }, behavior: partial_fill, fills: ["40%%", "10%%"], then: leave }
    - { name: h-to-j-cancel, match: { first_letter: "H-J" }, behavior: cancel_after_ack }
    - { name: k-to-m-reject, match: { first_letter: "K-M" }, behavior: reject, reject_code: 0, text: "Rejected by OrderEcho rule" }
    - { name: odd-lots, match: { first_letter: "N-P" }, behavior: partial_fill, fills: [1, 2, 3, 405], then: fill_rest }
    - { name: default, match: { any: true }, behavior: full_fill }
sessions:
  - { id: agent42, fix_version: FIX.4.2, sender_comp_id: ORDERECHO, target_comp_id: AGENT }
  - { id: agent44, fix_version: FIX.4.4, sender_comp_id: ORDERECHO, target_comp_id: AGENT }
  - id: strict-broker
    fix_version: FIX.4.2
    sender_comp_id: STRICTBRK
    target_comp_id: AGENT
    port: %d
    price_band: { pct: 2, on_no_reference: reject }
    rules:
      - { name: reject-all, match: { any: true }, behavior: reject, reject_code: 0, text: "Strict broker rejects everything" }
storage: { seqnum_dir: %q, evidence_dir: %q, msgstore_dir: %q }
logging: { log_dir: %q, fix_delimiter: "|", engine_level: DEBUG, console: false }
control_api: { enabled: true, host: 127.0.0.1, port: %d }
pricing: { mode: static, static: { AAPL: 227.50, default: 100.00 } }
`

func startEmulator(t *testing.T) *emulator {
	t.Helper()
	requireEmulator(t)
	e := &emulator{t: t, dir: filepath.Join(t.TempDir(), "emulator"), out: &lockedBuffer{}}
	e.fixPort, e.strictPort, e.apiPort = freePort(t), freePort(t), freePort(t)
	for e.strictPort == e.fixPort || e.apiPort == e.fixPort || e.apiPort == e.strictPort {
		e.strictPort, e.apiPort = freePort(t), freePort(t)
	}
	os.MkdirAll(e.dir, 0o755)
	cfgPath := filepath.Join(e.dir, "emulator.yaml")
	cfg := fmt.Sprintf(emulatorConfig, e.fixPort, e.strictPort,
		filepath.Join(e.dir, "data", "seqnums"), filepath.Join(e.dir, "data", "evidence"),
		filepath.Join(e.dir, "data", "msgstore"), filepath.Join(e.dir, "logs"), e.apiPort)
	if err := os.WriteFile(cfgPath, []byte(cfg), 0o644); err != nil {
		t.Fatal(err)
	}
	e.cmd = exec.Command(pythonBin, filepath.Join(emulatorDir, "orderecho_Main.py"), "--config", cfgPath)
	e.cmd.Dir = e.dir // relative paths never land in the emulator's folder
	// No .pyc writes into the emulator's folder.
	e.cmd.Env = append(os.Environ(), "PYTHONDONTWRITEBYTECODE=1", "PYTHONUNBUFFERED=1")
	e.cmd.Stdout, e.cmd.Stderr = e.out, e.out
	if err := e.cmd.Start(); err != nil {
		t.Fatalf("starting emulator: %v", err)
	}
	exited := make(chan struct{})
	go func() { e.cmd.Wait(); close(exited) }()
	t.Cleanup(func() {
		e.cmd.Process.Signal(syscall.SIGTERM)
		select {
		case <-exited:
		case <-time.After(15 * time.Second):
			e.cmd.Process.Kill()
			<-exited
		}
		if t.Failed() {
			t.Logf("emulator output:\n%s", e.out.String())
			for _, p := range globAll(filepath.Join(e.dir, "logs", "engine", "*.log")) {
				data, _ := os.ReadFile(p)
				t.Logf("emulator engine log %s:\n%s", p, data)
			}
		}
	})
	deadline := time.Now().Add(30 * time.Second)
	for {
		select {
		case <-exited:
			t.Fatalf("emulator exited during startup:\n%s", e.out.String())
		default:
		}
		resp, err := httpClient.Get(e.url("/health"))
		if err == nil {
			resp.Body.Close()
			if resp.StatusCode == 200 {
				break
			}
		}
		if time.Now().After(deadline) {
			t.Fatalf("emulator /health never answered:\n%s", e.out.String())
		}
		time.Sleep(100 * time.Millisecond)
	}
	t.Logf("emulator up: fix=%d strict=%d api=%d dir=%s", e.fixPort, e.strictPort, e.apiPort, e.dir)
	return e
}

func globAll(pattern string) []string { m, _ := filepath.Glob(pattern); return m }

// httpClient never keeps connections alive, so the emulator's HTTP server can
// shut down at once.
var httpClient = &http.Client{Timeout: 10 * time.Second, Transport: &http.Transport{DisableKeepAlives: true}}

func (e *emulator) url(path string) string {
	return fmt.Sprintf("http://127.0.0.1:%d%s", e.apiPort, path)
}

func (e *emulator) post(path string, body any) map[string]any {
	e.t.Helper()
	var r io.Reader = strings.NewReader("{}")
	if body != nil {
		data, _ := json.Marshal(body)
		r = bytes.NewReader(data)
	}
	resp, err := httpClient.Post(e.url(path), "application/json", r)
	if err != nil {
		e.t.Fatalf("POST %s: %v", path, err)
	}
	defer resp.Body.Close()
	data, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != 200 {
		e.t.Fatalf("POST %s -> %d %s", path, resp.StatusCode, data)
	}
	var out map[string]any
	json.Unmarshal(data, &out)
	e.t.Logf("POST %s -> %s", path, strings.TrimSpace(string(data)))
	return out
}

func (e *emulator) getJSON(path string, into any) {
	e.t.Helper()
	resp, err := httpClient.Get(e.url(path))
	if err != nil {
		e.t.Fatalf("GET %s: %v", path, err)
	}
	defer resp.Body.Close()
	json.NewDecoder(resp.Body).Decode(into)
}

type emuStatus struct {
	State            string `json:"state"`
	NextOut          int    `json:"next_out"`
	NextIn           int    `json:"next_in"`
	PendingTestReqID string `json:"pending_test_req_id"`
	FixLogPath       string `json:"fix_log_path"`
}

func (e *emulator) status(id string) emuStatus {
	e.t.Helper()
	resp, err := httpClient.Get(e.url("/sessions/" + id + "/status"))
	if err != nil {
		e.t.Fatalf("status: %v", err)
	}
	defer resp.Body.Close()
	var s emuStatus
	json.NewDecoder(resp.Body).Decode(&s)
	return s
}

func (e *emulator) fixLog(id string) string {
	var all []string
	for _, p := range globAll(filepath.Join(e.dir, "logs", "fix", id+"_*.log")) {
		data, _ := os.ReadFile(p)
		all = append(all, string(data))
	}
	return strings.Join(all, "")
}

// --------------------------------------------------------------- agent

type agentSpec struct {
	id, version, target string
	port                int
	reset, reconnect    bool
}

type agent struct {
	t      *testing.T
	dir    string
	id     string
	ini    *transport.Initiator
	res    chan transport.Result
	cancel context.CancelFunc
	ev     *evidence.Writer
	fixLog *logs.FixLog
	engine *logs.EngineLog
	ag     *oeagent.Agent
	events chan session.Evidence
	result *transport.Result
}

var runSeq struct {
	sync.Mutex
	n int
}

// uniqueRunID keeps ClOrdIDs unique across every agent one emulator sees.
func uniqueRunID(id string) string {
	runSeq.Lock()
	defer runSeq.Unlock()
	runSeq.n++
	return fmt.Sprintf("%s-%s%d", evidence.MakeRunID(time.Now()), strings.ReplaceAll(id, "-", ""), runSeq.n)
}

func startAgent(t *testing.T, spec agentSpec) *agent {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "agent-"+spec.id)
	a := &agent{t: t, dir: dir, id: spec.id, res: make(chan transport.Result, 1), events: make(chan session.Evidence, 4096)}
	cfg := &config.Config{
		Storage: config.Storage{SeqnumDir: filepath.Join(dir, "data", "seqnums"), MsgstoreDir: filepath.Join(dir, "data", "msgstore"),
			EvidenceDir: filepath.Join(dir, "data", "evidence")},
		Logging: config.Logging{LogDir: filepath.Join(dir, "logs"), FixDelimiter: "|", EngineLevel: "DEBUG"},
	}
	sc := config.Session{ID: spec.id, FixVersion: spec.version, SenderCompID: "AGENT", TargetCompID: spec.target,
		Host: "127.0.0.1", Port: spec.port, HeartbeatSec: 30, ResetOnLogon: spec.reset,
		Defaults: config.Defaults{LogonTimeoutSec: 10, LogoutTimeoutSec: 10, HeartbeatGracePct: 20,
			Reconnect: spec.reconnect, ReconnectIntervalSec: 0.5, HeartbeatMismatch: "warn",
			IncludeHandlInst: true, ClOrdIDPrefix: "IT"}}
	cfg.Sessions = []config.Session{sc}
	ag, err := oeagent.New(oeagent.Options{Config: cfg, Session: sc, Clock: clock.SystemClock{}, RunID: uniqueRunID(spec.id),
		Tick: 100 * time.Millisecond,
		OnEvidence: func(e session.Evidence) {
			select {
			case a.events <- e:
			default:
			}
		}})
	if err != nil {
		t.Fatal(err)
	}
	a.ag, a.ini, a.ev, a.fixLog, a.engine = ag, ag.Init, ag.Evidence, ag.FixLog, ag.EngineLog
	ctx, cancel := context.WithCancel(context.Background())
	a.cancel = cancel
	go func() { a.res <- ag.Run(ctx) }()
	t.Cleanup(func() {
		a.ini.Stop("test cleanup")
		cancel()
		a.wait(10 * time.Second)
		ag.Close()
		if t.Failed() {
			data, _ := os.ReadFile(a.fixLogPath())
			t.Logf("agent FIX log:\n%s", data)
			for _, p := range globAll(filepath.Join(dir, "logs", "engine", "*.log")) {
				data, _ := os.ReadFile(p)
				t.Logf("agent engine log:\n%s", data)
			}
		}
	})
	return a
}

func (a *agent) snap() transport.Snapshot { return a.ini.Snapshot() }

func (a *agent) fixLogPath() string {
	return a.fixLog.PathFor(time.Now())
}

func (a *agent) waitActive(timeout time.Duration, logons int) {
	a.t.Helper()
	waitFor(a.t, timeout, fmt.Sprintf("%s logon #%d", a.id, logons), func() bool {
		s := a.snap()
		return s.State == session.Active && s.Logons >= logons
	})
}

// wait returns Run's result (once), or fails after timeout.
func (a *agent) wait(timeout time.Duration) transport.Result {
	if a.result != nil {
		return *a.result
	}
	select {
	case r := <-a.res:
		a.result = &r
		return r
	case <-time.After(timeout):
		a.t.Fatalf("agent %s did not finish within %s", a.id, timeout)
	}
	return transport.Result{}
}

// testRequestRoundTrip sends a TestRequest and waits for its Heartbeat.
func (a *agent) testRequestRoundTrip() {
	a.t.Helper()
	id, err := a.ini.TestRequest()
	if err != nil {
		a.t.Fatalf("TestRequest: %v", err)
	}
	waitFor(a.t, 5*time.Second, "Heartbeat answering "+id, func() bool {
		return a.snap().PendingTestReqID == ""
	})
	data, _ := os.ReadFile(a.fixLogPath())
	if !strings.Contains(string(data), "|112="+id+"|") || !regexpIn(string(data), `IN\s+seq=\d+\s+35=0\s+.*\|112=`+id+`\|`) {
		a.t.Fatalf("no inbound Heartbeat with 112=%s in agent FIX log", id)
	}
	a.t.Logf("%s: TestRequest %s answered", a.id, id)
}

// inSync waits until both sides agree on the sequence numbers.
func inSync(t *testing.T, a *agent, e *emulator, emuID string) {
	t.Helper()
	var last string
	waitFor(t, 5*time.Second, "sequence numbers in sync", func() bool {
		s, es := a.snap(), e.status(emuID)
		last = fmt.Sprintf("agent next_out=%d next_in=%d / emulator next_in=%d next_out=%d (%s)", s.NextOut, s.NextIn, es.NextIn, es.NextOut, es.State)
		return es.State == "ACTIVE" && s.State == session.Active && s.NextOut == es.NextIn && s.NextIn == es.NextOut
	})
	t.Logf("in sync: %s", last)
}

// --------------------------------------------------------------- CLI

const agentConfig = `sessions:
  - { id: emu42,  fix_version: FIX.4.2, sender_comp_id: AGENT, target_comp_id: ORDERECHO, host: 127.0.0.1, port: %[1]d, heartbeat_sec: 30, reset_on_logon: true }
  - { id: emu44,  fix_version: FIX.4.4, sender_comp_id: AGENT, target_comp_id: ORDERECHO, host: 127.0.0.1, port: %[1]d, heartbeat_sec: 30, reset_on_logon: true }
  - { id: strict, fix_version: FIX.4.2, sender_comp_id: AGENT, target_comp_id: STRICTBRK, host: 127.0.0.1, port: %[2]d, heartbeat_sec: 30, reset_on_logon: true }
  - { id: strict44, fix_version: FIX.4.4, sender_comp_id: AGENT, target_comp_id: STRICTBRK, host: 127.0.0.1, port: %[2]d, heartbeat_sec: 30, reset_on_logon: true }
  - { id: unknown, fix_version: FIX.4.2, sender_comp_id: NOBODY, target_comp_id: ORDERECHO, host: 127.0.0.1, port: %[1]d, heartbeat_sec: 30, reset_on_logon: true }
defaults: { logon_timeout_sec: 10, logout_timeout_sec: 10, heartbeat_grace_pct: 20, reconnect: false, reconnect_interval_sec: 1 }
storage: { seqnum_dir: data/seqnums, msgstore_dir: data/msgstore, evidence_dir: data/evidence }
logging: { log_dir: logs, fix_delimiter: "|", engine_level: INFO, console: true }
`

// cliDir writes an agent config for e into a fresh directory and returns it.
func cliDir(t *testing.T, e *emulator) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "cli")
	os.MkdirAll(dir, 0o755)
	if err := os.WriteFile(filepath.Join(dir, "orderecho.yaml"), []byte(fmt.Sprintf(agentConfig, e.fixPort, e.strictPort)), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

type cliRun struct {
	code int
	out  string
}

func runCLI(t *testing.T, dir string, timeout time.Duration, args ...string) cliRun {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	cmd := exec.CommandContext(ctx, agentBin, append([]string{"--config", "orderecho.yaml"}, args...)...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	code := 0
	if err != nil {
		var ee *exec.ExitError
		if !asExitError(err, &ee) {
			t.Fatalf("running CLI: %v\n%s", err, out)
		}
		code = ee.ExitCode()
	}
	if ctx.Err() != nil {
		t.Fatalf("CLI timed out:\n%s", out)
	}
	t.Logf("$ orderecho %s  -> exit %d\n%s", strings.Join(args, " "), code, out)
	return cliRun{code: code, out: string(out)}
}

func asExitError(err error, target **exec.ExitError) bool {
	e, ok := err.(*exec.ExitError)
	if ok {
		*target = e
	}
	return ok
}
